import { createTheme, rem } from '@mantine/core';

export const theme = createTheme({
  primaryColor: 'torrent',
  primaryShade: 6,
  colors: {
    torrent: [
      '#eff6ff',
      '#dbeafe',
      '#bfdbfe',
      '#93c5fd',
      '#60a5fa',
      '#3b82f6',
      '#2563eb',
      '#1d4ed8',
      '#1e40af',
      '#1e3a8a',
    ],
    success: [
      '#f0fdfa',
      '#ccfbf1',
      '#99f6e4',
      '#5eead4',
      '#2dd4bf',
      '#14b8a6',
      '#0f766e',
      '#115e59',
      '#134e4a',
      '#042f2e',
    ],
    danger: [
      '#fff1f2',
      '#ffe4e6',
      '#fecdd3',
      '#fda4af',
      '#fb7185',
      '#f43f5e',
      '#b42318',
      '#9f1239',
      '#881337',
      '#4c0519',
    ],
  },
  fontFamily: 'system-ui, -apple-system, BlinkMacSystemFont, "PingFang SC", "Microsoft YaHei", sans-serif',
  headings: {
    fontFamily: 'system-ui, -apple-system, BlinkMacSystemFont, "PingFang SC", "Microsoft YaHei", sans-serif',
    fontWeight: '700',
  },
  fontFamilyMonospace: '"SFMono-Regular", Consolas, "Liberation Mono", monospace',
  defaultRadius: 'md',
  radius: {
    sm: rem(8),
    md: rem(10),
    lg: rem(14),
  },
  shadows: {
    sm: '0 2px 8px rgba(23, 32, 51, 0.06)',
    md: '0 12px 30px rgba(23, 32, 51, 0.1)',
  },
});
