[global]
	server role = standalone server
	security = user
	map to guest = never
	restrict anonymous = 2
	smb ports = 445
	disable netbios = yes
	server min protocol = SMB2_10
	load printers = no
	printing = bsd
	printcap name = /dev/null
	disable spoolss = yes
	log level = 1
	logging = stderr
	max log size = 0
	pid directory = /run/samba
	lock directory = /run/samba/lock
	state directory = /run/samba/state
	cache directory = /run/samba/cache
	private dir = /run/samba/private
	log file = /run/samba/log.%m
	passdb backend = tdbsam

[torrentfs]
	path = /mnt/torrentfs
	browseable = yes
	read only = yes
	guest ok = no
	valid users = __TORRENTFS_SMB_USER__
	force user = __TORRENTFS_SMB_USER__
	force group = __TORRENTFS_SMB_GROUP__
	nt acl support = no
